### ISSUE TITLE
Define artifact name rules, file name rules or tracing rules in config file instead of hardcoding

### ISSUE THREAD

**Issue by Godsmith** [regot-chalmers/treqs#33]
**Is your feature request related to a problem? Please describe.**
Right now, the framework is not very flexible - you must have test cases traced to requirements and use cases, and requirements traced to use cases. And if you want to avoid specify the requirement file name and id format every time you are running treqs, you have to modify the source code.

**Describe the solution you'd like**
Artifact names, id conventions, file name conventions, and tracing should be able to be defined on a per-project basis, for example in YAML format in a file called ".treqs.yml" (similar to .travis.yml files used for Travis CI or appveyor.yml for AppVeyor). E.g.

```
- artifact:
  - name: Requirement
  - id: REQ\.*$
  - file-name: SR_.*\.md$
- artifact:
  - name: Test Case
  - id: TC\.*$
  - file-name: TC_.*\.md$
[...]
traces:
- Requirement-User Story
- Test Case - Requirement 
```

**Describe alternatives you've considered**
Another file format than YAML would be perfectly fine.

**Additional context**
